### PR TITLE
[production/RRFS.v1] Update DA task names in workflow, cleanup modulefiles

### PR DESCRIPTION
**Pull request by BenjaminBlake-NOAA**
## DESCRIPTION OF CHANGES: 

- In this PR, the task names for some of the DA tasks in the workflow have been updated, often to remove the "run_" prefixes.  This involves changes to the names of J-jobs/ex-scripts.  The list of task name changes is as follows:
- run_prepstart -> prep_cyc
- process_radarref -> process_radar
- process_glmfed -> process_lightning
- run_analysis -> analysis_gsi
- run_gsidiag -> analysis_gsidiag
- run_enkf -> analysis_enkf
- run_nonvarcldanl -> analysis_nonvarcld
- run_recenter -> recenter
- run_postanal -> update_lbc_soil
- run_bufrsnd -> bufrsnd

- These task name updates also involve changes to numerous variables across different files in the workflow, including FV3LAM_wflow.xml and ush files.  In addition, some variable names did not directly correspond to the task names (e.g. PROC_BUFR for PROCESS_BUFR) so those inconsistencies were also resolved.
- Some cleanup to the modulefiles directory is also included with this PR.  Modulefiles had to be renamed with the task name changes, and some unneeded modulefiles were removed from the workflow (e.g. run_graphics, run_vx).
-  A fix to the DA engineering test is also included - PREP_CYC_SPINUP was incorrectly set as PREP_CYC_SPINUP_ensinit.

## TESTS CONDUCTED: 

A spinup cycle with the DA engineering test completed successfully on Cactus. The xmls for the DA engineering test and real-time parallel experiments were built successfully with the DA engineering test fix.

### Machines/Platforms:

- WCOSS2
  - [x] Cactus/Dogwood
  - [ ] Acorn
- RDHPCS
  - [ ] Hera
  - [ ] Jet
  - [ ] Orion
  - [ ] Hercules

### Test cases: 

- [x] Engineering tests
  - [ ] Non-DA engineering test
  - [x] DA engineering test
    - [ ] Retro
    - [ ] Ensemble
    - [x] Parallel
- [ ] RRFS fire weather
- [ ] RRFS_A:
- [ ] RRFS_B:
- [ ] RTMA:
- [ ] Others:

## ISSUE: 

- Fixes issue #247

### CODE REVIEW

**Review by MatthewPyle-NOAA — COMMENTED** [review]
The only renames that gave me some pause were for radar and lightning tasks (maybe being too generic).  But since these are for the production RRFSv1 workflow, it shouldn't be a worry.  

I'd vote for fixing the engineering tests within this PR, unless that fix is too extensive.

**Comment by BenjaminBlake-NOAA** [comment]
@MatthewPyle-NOAA The process_radar and process_lightning task renames did make them more generic and less specific, but if the previous names (process_radarref, process_glmfed) make more sense, or you'd prefer a different variation, I'm happy to make those changes.

I had to think about the best way to fix the DA engineering test, but was able to come up with something which I will test today.

**Comment by MatthewPyle-NOAA** [comment]
@BenjaminBlake-NOAA Is this ready to go now?

**Comment by BenjaminBlake-NOAA** [comment]
@MatthewPyle-NOAA Yes I committed the fix for the DA engineering test yesterday.  In FV3LAM_wflow.xml there is a new condition like this: if not ensinit, then do the prep_cyc_spinup task.  The xmls for the DA engineering test and real-time parallels built successfully.

**Review by MatthewPyle-NOAA — APPROVED** [review]
Now that the DA engineering test is fixed, will approve and merge.  Thanks, Ben!

**Pull request merged**
