### PR TITLE
EE2 modifications to J-job, ex-script, ush script hierarchy

### PR DESCRIPTION
**Pull request by BenjaminBlake-NOAA**
## DESCRIPTION OF CHANGES: 

- One EE2-specific change is to make sure that no J-jobs directly call a ush script, and utility scripts (scripts called by another script) are in ush.  J-jobs should only call ex-scripts directly.  I went through all of the J-jobs/ex-scripts in the workflow and found a few issues that will need to be resolved.  I am thinking these changes would be better to add to a future RRFSv1 production branch and not dev-sci (see items 4-6 below), so I am going to leave this PR as a draft for now.
1. The exrrfs_run_prepstart,sh script calls exrrfs_prep_fvcom.sh.  exrrfs_prep_fvcom.sh is moved to ush and renamed to fvcom_prep.sh.
2. exrrfs_save_restart.sh calls exrrfs_process_glmfed.py, which is also in the scripts directory.  I would move this script to ush, however it is also called by another J-job, JRRFS_PROCESS_GLMFED.  So it is unclear how to resolve this.
3. All of the J-jobs and ex-scripts call ush/source_util_funcs.sh.  The J-jobs should not be calling any utility scripts.  Removing it would be a larger change so maybe that should be done as part of a separate PR.
4. JRRFS_MAKE_ICS and JRRFS_MAKE_LBCS call ush/get_extrn_mdl_file_dir_info.sh.  I think this script should be removed, and the relevant changes needed for RRFSv1 should be moved directly into the J-jobs.  However I think this change should be made to a RRFSv1 production branch and not dev-sci.
5. exrrfs_archive_emc.ksh and exrrfs_archive_ens.ksh do not have corresponding J-jobs.  These scripts can be removed, but this change should be made to a RRFSv1 production branch.
6.  JRRFS_IODA_PREPBUFR, JRRFS_JEDIENVAR_IODA, and JRRFS_RUN_PYTHON_GRAPHICS are not needed for RRFSv1.  These J-jobs and ex-scripts can be removed, but this change should be made to a RRFSv1 production branch.

## TESTS CONDUCTED: 

The re-located script change included here was not tested.

### Machines/Platforms:

- WCOSS2
  - [ ] Cactus/Dogwood
  - [ ] Acorn
- RDHPCS
  - [ ] Hera
  - [ ] Jet
  - [ ] Orion
  - [ ] Hercules

### Test cases: 

- [ ] Engineering tests
  - [ ] Non-DA engineering test
  - [ ] DA engineering test
    - [ ] Retro
    - [ ] Ensemble
    - [ ] Parallel
- [ ] RRFS fire weather
- [ ] RRFS_A:
- [ ] RRFS_B:
- [ ] RTMA:
- [ ] Others:

## ISSUE: 

- Starts to fix issue #242

### CODE REVIEW

**Comment by BenjaminBlake-NOAA** [comment]
@MatthewPyle-NOAA  When you get a chance, please take a look at items 2-6 and we can discuss how to best resolve them.  Thanks!

**Comment by MatthewPyle-NOAA** [comment]
@BenjaminBlake-NOAA Doing 4-6 as part of a release branch cleanup makes sense to me.  

2) exrrfs_save_restart.sh calls exrrfs_process_glmfed.py, which is also in the scripts directory. I would move this script to ush, however it is also called by another J-job, JRRFS_PROCESS_GLMFED. So it is unclear how to resolve this.

_- Without looking at the details of JRRFS_PROCESS_GLMFED, I had the thought of adding a simple ex-script to stand between the J-job and now ush/exrrfs_process_glmfed.py.  Another possibility would be to have the same content with different names in scripts/ and ush/.  I think I'd also need to look at why the exrrfs_save_restart.sh script calls the exrrfs_process_glmfed.py script._ 

3)All of the J-jobs and ex-scripts call ush/source_util_funcs.sh. The J-jobs should not be calling any utility scripts. Removing it would be a larger change so maybe that should be done as part of a separate PR.

_- Definitely agree with doing this as a separate PR._

**Comment by BenjaminBlake-NOAA** [comment]
@MatthewPyle-NOAA  I will wait to mark this PR as ready for review until the production/wcoss2 branch is opened.  With it I can also include items 4-6.

Regarding item 2, it looks like exrrfs_save_restart.sh calls exrrfs_process_glmfed.py if the EnVar needs the flash extent density saved in either the control or ensemble members.  I'm not too familiar with this.  Adding a simple ex-script for JRRFS_PROCESS_GLMFED could work, and then the current exrrfs_process_glmfed.py would be moved into ush and renamed.

**Comment by BenjaminBlake-NOAA** [comment]
@MatthewPyle-NOAA  I am going to close this PR but will submit two PRs tomorrow for some of these changes to the production/RRFS branch:
1. Cleanup PR - includes items 1, 5, and 6 listed here.  This one should be simple to review.
2. Remove get_extrn_mdl_file_dir_info.sh and unneeded input data options, and change FV3GFS to GFS.  This one is more complicated and will change a lot of files (~30-40).

**Pull request closed without merging**
