### PR TITLE
Expand the surface varialbe list for recentering

### PR DESCRIPTION
**Pull request by chunhuazhou**
## DESCRIPTION OF CHANGES: 
Expand the surface variable list for recentering

## TESTS CONDUCTED: 
Tested in retro runs on Jet.

## CONTRIBUTORS (optional): 
Thanks much to Tanya Smirnova for compiling the surface variable list!

### CODE REVIEW

**Comment by MatthewPyle-NOAA** [comment]
@ShunLiu-NOAA @hu5970  - Are you good with this expanded list of variables?

**Comment by ShunLiu-NOAA** [comment]
We should expand surface variable list ASAP to bring DET surface to EnKF/EnFCST cycle.

**Review by ShunLiu-NOAA — APPROVED** [review]

**Comment by chunhuazhou** [comment]
Thanks for the quick actions! I should mention that a minor change to rrfs_utl has been merged and is needed for this expanded variable list to work.

**Comment by hu5970** [comment]
Thanks for getting this into the rrfs-workflow.

**Comment by guoqing-noaa** [comment]
> Thanks for the quick actions! I should mention that a minor change to rrfs_utl has been merged and is needed for this expanded variable list to work.

@chunhuazhou FYI, you would have been able to change the rrfs_utl hash in this PR as ufs-srweather-app and regional_worfkow were already merged into one piece.

**Pull request merged**
