### PR TITLE
update build_orion_intel.lua for spack-stack v1.5.0

### PR DESCRIPTION
**Pull request by guoqing-noaa**
update build_orion_intel.lua for spack-stack v1.5.0
This change only affects Orion and compiling tested on Orion.

## ISSUE: 

- Fixes the issue(s) mentioned in #145

### CODE REVIEW

**Review by MatthewPyle-NOAA — APPROVED** [review]

**Comment by chan-hoo** [comment]
@guoqing-noaa, I got the following error:
```
... Load MODULE_FILE and create BUILD directory ...
Lmod has detected the following error:  Unable to load module because of error when evaluating modulefile:
     /work/noaa/rtrr/gge/lua/wrf_io/1.2.0a.lua: Empty or non-existant file
     Please check the modulefile and especially if there is a the line number specified in the above message
While processing the following module(s):
    Module fullname    Module Filename
    ---------------    ---------------
    wrf_io/1.2.0a      /work/noaa/rtrr/gge/lua/wrf_io/1.2.0a.lua
    build_orion_intel  /work/noaa/fv3-cam/chjeon/rrfs_test/rrfs-workflow/sorc/../modulefiles/build_orion_intel.lua
```

**Comment by guoqing-noaa** [comment]
Thanks for testing. Let me check again.

**Comment by guoqing-noaa** [comment]
@chan-hoo Could you try it again?  It was a file permission issue and is now fixed.

**Comment by chan-hoo** [comment]
@guoqing-noaa, I confirmed that it was compiled successfully on Orion. Thanks for the pr. Approving.

**Review by chan-hoo — APPROVED** [review]

**Pull request merged**
