### PR TITLE
Updating UPP hash for latest code.

### PR DESCRIPTION
**Pull request by EricJames-NOAA**
## DESCRIPTION OF CHANGES: 
Update UPP hash and fix files for the top of the UPP develop branch.  

## TESTS CONDUCTED: 
A test for RRFS_NA_3km was conducted with the previous UPP used for RRFS vs. the new UPP.  The only differences are additions of expected fields, and a change to the GUST value (also expected based on a recent commit).  

### Machines/Platforms:

- WCOSS2
  - [ ] Cactus/Dogwood
  - [ ] Acorn
- RDHPCS
  - [x] Hera
  - [ ] Jet
  - [ ] Orion
  - [ ] Hercules

### Test cases: 

- [ ] Engineering tests
  - [ ] Non-DA engineering test
  - [ ] DA engineering test
    - [ ] Retro
    - [ ] Ensemble
    - [ ] Parallel
- [ ] RRFS fire weather
- [x] RRFS_A: one-off UPP test
- [ ] RRFS_B:
- [ ] RTMA:
- [ ] Others:

## ISSUE: 
None

### CODE REVIEW

**Review by MatthewPyle-NOAA — APPROVED** [review]
Will approve it on faith, but is this adding another 3D field to the NATLEV file as it appears?

**Comment by EricJames-NOAA** [comment]
> Will approve it on faith, but is this adding another 3D field to the NATLEV file as it appears?

@MatthewPyle-NOAA yes.  We can discuss this...it was requested by the smoke/dust folks.  If we don't add this field, we are only providing two of the three aerosol species (smoke and fine dust) but not the third (coarse dust).  We already have all three in the pressure level files.

**Comment by MatthewPyle-NOAA** [comment]
Will get it merged for the other needed changes - we can pull out the new dust field on model level later if needed.  But probably good to discuss at a coming RRFS meeting.

**Comment by EricJames-NOAA** [comment]
> Will get it merged for the other needed changes - we can pull out the new dust field on model level later if needed. But probably good to discuss at a coming RRFS meeting.

Sounds good.  Thanks!

**Pull request merged**
