### PR TITLE
bug fix to saturation calculation

### PR DESCRIPTION
**Pull request by hu5970**
1. update rrfs_utl hash to include bug fix to saturation calculation.
2. small bug fix in exrrfs_process_bufr.sh to write output
3. update RRFS_A run time.

Tested with RRFS_A.

### CODE REVIEW

**Review by MatthewPyle-NOAA — APPROVED** [review]
All looks good to me - thanks for getting the saturation calculation fixed so quickly.

**Comment by guoqing-noaa** [comment]
@hu5970 Will this affect RTMA?

**Comment by hu5970** [comment]
@guoqing-noaa Should not impact results noticeable.

**Comment by guoqing-noaa** [comment]
> @guoqing-noaa Should not impact results noticeable.

Good to know. Thanks!

**Pull request merged**
