### PR TITLE
Remove _vrfy from basic unix commands in scripts

### PR DESCRIPTION
**Pull request by chan-hoo**
## DESCRIPTION OF CHANGES: 

- Remove `_vrfy` from `cp_vrfy`, `mv_vrfy`, `mkdir_vrfy`, `ln_vrfy`, and `rm_vrfy`.

## TESTS CONDUCTED: 

- On machines/platforms:

- [ ] WCOSS2
- [x] Hera
- [ ] Orion
- [ ] Jet

- Test cases: 

- [x] Non-DA engineering test
- [x] DA engineering test
- [ ] Other sample scripts:

## ISSUE: 

- Fixes the issue(s) mentioned in #35

### CODE REVIEW

**Review by BenjaminBlake-NOAA — APPROVED** [review]
@chan-hoo  I tried running my test with the RRFS_CONUS_3km grid and got a "Cannot place all ranks on node list" error.  My test was successful when I re-ran with the RRFS_CONUS_25km grid though, so I'm approving these changes since they are unrelated to the error I got.  Should I open an issue for fixing the 3-km grid?

**Comment by chan-hoo** [comment]
@BenjaminBlake-NOAA, can you point me to your `config.sh` for RRFS_CONUS_3km?

**Comment by BenjaminBlake-NOAA** [comment]
@chan-hoo I used the sample_configs/non-DA_eng/config.nonDA.grib2.wcoss2.sh file and simply changed the grid to RRFS_CONUS_3km.  I see many other config files in the sample_configs directory, such as the ones for RRFS_A, and one of those is for the 3-km CONUS grid.  So maybe an issue is not needed and I shouldn't be modifying the grid in the non-DA_eng config file?

**Comment by chan-hoo** [comment]
@BenjaminBlake-NOAA, I'll test it. I also sometimes got the same error in run_task on wcoss2. Whenever I got this error, I changed  `<!ENTITY NATIVE_ALL    "<native>-l place=excl</native>">` to `place=vscatter` to resolve it. As you said, the DA samples doesn't seem to have this issue. So I'll parameterize this parameter for run_post and set it by default only for the non-DA test.

**Comment by BenjaminBlake-NOAA** [comment]
@chan-hoo Ahh ok, yeah I think the vscatter setting should fix it.  I think I also got the same error with my make_ics job the first time, but the re-run was successful.  I wonder why it only happens sometimes and not others.

**Review by MatthewPyle-NOAA — DISMISSED** [review]
Looks good to me - very straightforward changes and easy to review.  One thought on the bulk switch from cp_vrfy to cp is losing a check that things were properly copied.  Not critical now, but eventually we'll probably want to add some cpreq calls for critical items, or have other error checking on some of the files being copied into the run directory (more for model generated files, not so much for static items coming from fix/ or parm/ files).

**Comment by MatthewPyle-NOAA** [comment]
Actually did one sanity check after approving, and noticed that some _vrfy items remain in the branch:

in scripts:

exregional_make_grid.sh:cd_vrfy -
exregional_make_grid.sh:mv_vrfy ${shaved_fp} ${GRID_DIR}
exregional_make_grid.sh:mv_vrfy ${shaved_fp} ${GRID_DIR}
exregional_make_grid.sh:mv_vrfy ${shaved_fp} ${GRID_DIR}
exregional_make_grid.sh:cd_vrfy -
exregional_make_orog.sh:cd_vrfy -
exregional_make_orog.sh:cd_vrfy -
exregional_make_orog.sh:cd_vrfy -

In ush:

link_fix.sh:  cd_vrfy -

**Comment by chan-hoo** [comment]
@MatthewPyle-NOAA, I've added some missing change in `make_grid`. As you mentioned, I'll check what `cd_vrfy -` means exactly. Do you think it should be the same as `cd -`?

**Comment by MatthewPyle-NOAA** [comment]
@chan-hoo "cd -" was new to me as well, but it appears to switch back to the previous directory as indicated in the comments.

I started here:

/lfs/h2/emc/ptmp/emc.lam

cd rrfs/v0.6.7/prod/rrfs.20230918

pwd:
/lfs/h2/emc/ptmp/emc.lam/rrfs/v0.6.7/prod/rrfs.20230918

cd -
pwd:
/lfs/h2/emc/ptmp/emc.lam

**Comment by chan-hoo** [comment]
@MatthewPyle-NOAA, it worked as expected. The non-da test was completed successfully with the last change.

**Review by MatthewPyle-NOAA — APPROVED** [review]
Approving again after the last few _vrfy items were cleaned out.

Will repeat my comment from my previous review that we'll want to add cpreq copies or other error checking on critical items being copied into the run directory.  But that can wait for the future.

**Pull request merged**
