### PR TITLE
Remove RUN_ENVIR and community mode

### PR DESCRIPTION
**Pull request by chan-hoo**
## DESCRIPTION OF CHANGES: 

- Remove `RUN_ENVIR`.
- Clean up the `community` mode.
- Convert `community` to `nco` in the non-DA sample scripts

## TESTS CONDUCTED: 

- On machines/platforms:

- [x] WCOSS2
- [x] Hera
- [x] Orion
- [ ] Jet

- Test cases: 

- [x] Non-DA engineering test
- [x] DA engineering test (on Hera)
- [ ] Other sample scripts:

## ISSUE: 

- Fixes the issue(s) mentioned in #47

### CODE REVIEW

**Comment by MatthewPyle-NOAA** [comment]
@chan-hoo Thanks for the clarification about the purpose for this one.  Everything looks pretty good to me just looking at the changes.  One question I had has to do with the shifting of several scripts from "set +x" to "set -x".  I know that is preferred/required by NCO, but just curious if it creates any very long log files with the change.

**Review by MatthewPyle-NOAA — APPROVED** [review]
Looks good from my perspective

**Comment by MatthewPyle-NOAA** [comment]
Will wait to see if @BenjaminBlake-NOAA wants to weigh in before merging

**Comment by BenjaminBlake-NOAA** [comment]
@MatthewPyle-NOAA @chan-hoo  Yes I would like to review this PR before it gets merged if possible.  I should have time tomorrow to look over the changes.  Thanks

**Review by BenjaminBlake-NOAA — APPROVED** [review]
@chan-hoo  All the changes look good to me!  My only question would have been what Matt already asked about the set -x vs set +x difference.  I could run some tests with these changes if you'd like, but I don't think that is necessary and I don't want to hold up merging this PR.

**Comment by chan-hoo** [comment]
The only reason why I change to 'set -x' here is to follow the NCO standards (EE2 requirement) :) :)

**Pull request merged**
