### PR TITLE
Updates for UPP and python_graphics

### PR DESCRIPTION
**Pull request by jaymes-kenyon**
## DESCRIPTION OF CHANGES: 
- Updated hashes for UPP and python_graphics
- Updated static control files for UPP.  These updated files enable GRIB2 output of several fields, mainly to support aviation applications.

### Machines/Platforms:

- WCOSS2
  - [ ] Cactus/Dogwood
  - [ ] Acorn
- RDHPCS
  - [x ] Hera
  - [ ] Jet
  - [ ] Orion
  - [ ] Hercules

### Test cases: 

- [ ] Engineering tests
  - [ ] Non-DA engineering test
  - [ ] DA engineering test
    - [ ] Retro
    - [ ] Ensemble
    - [ ] Parallel
- [ ] RRFS fire weather
- [ ] RRFS_A:
- [ ] RRFS_B:
- [ ] RTMA:
- [ ] Others:

## ISSUE: 

- Fixes the issue(s) mentioned in #9999

## CONTRIBUTORS (optional): 
Updates to python_graphics were developed by @Brian-Jamison

### CODE REVIEW

**Review by MatthewPyle-NOAA — COMMENTED** [review]
There was another RRFS-related UPP PR merged today - could we update to hash 2953e46?

**Comment by jaymes-kenyon** [comment]
The latest UPP executable and control files ran successfully on Hera in a RRFS retro (CONUS domain).  Testing was limited to a single UPP job.  The associated UPP updates that I authored appear to be working as expected.  I cannot vouch for the functionality of other recent UPP changes (i.e., GTG-related fields, introduced in https://github.com/NOAA-EMC/UPP/pull/839), but the overall UPP job completed successfully.  Marking this PR as ready for review.

**Comment by MatthewPyle-NOAA** [comment]
@jaymes-kenyon Can you let me know what the new AVIATION datset is for?  Also, can you update your branch?  Thanks!

**Review by MatthewPyle-NOAA — APPROVED** [review]
Will fold this one in...

**Pull request merged**
