### PR TITLE
Updates for v0.7.9

### PR DESCRIPTION
**Pull request by hu5970**
Updates for v0.7.9:
    1) use module fms/2023.02.01
    2) turn on SDL/VDL in GSI analysis
    3) Use Halo 3 grid file for model forecast
    4) skip 07/19 EnKF DA product cycle (already changed before this PR).
    5) Turn on "DO_SAVE_DA_OUTPUT" for ensemble forecast cycles  to save the initial conditions after recenter.

### CODE REVIEW

**Comment by ShunLiu-NOAA** [comment]
@MatthewPyle-NOAA and @chan-hoo Could you please take a look at this PR? I want to update RRFS to v0.7.9 after the PR is merged. Thanks.

**Comment by MatthewPyle-NOAA** [comment]
> @MatthewPyle-NOAA and @chan-hoo Could you please take a look at this PR? I want to update RRFS to v0.7.9 after the PR is merged. Thanks.

I'm taking a look now, @ShunLiu-NOAA.  Thanks for the reminder.

**Review by MatthewPyle-NOAA — APPROVED** [review]
Looks like a safe one to me...approving.

**Review by ShunLiu-NOAA — COMMENTED** [review]
The changes looks reasonable and were already tested in dev0.7.9.

**Pull request merged**
