### PR TITLE
[production/RRFS.v1] Remove all references to JEDI and IODA from RRFSv1

### PR DESCRIPTION
**Pull request by BenjaminBlake-NOAA**
## DESCRIPTION OF CHANGES: 

- In PR #331 , the JEDIENVAR_IODA and IODA_PREPBUFR J-jobs and ex-scripts were removed.  In this PR, those tasks are removed from FV3LAM_wflow.xml, and all related variables are removed from files in the ush directory.  I was able to build the DA workflow successfully with these changes.

## TESTS CONDUCTED: 

Did not test any jobs but successfully built the workflow.

### Machines/Platforms:

- WCOSS2
  - [x] Cactus/Dogwood
  - [ ] Acorn
- RDHPCS
  - [ ] Hera
  - [ ] Jet
  - [ ] Orion
  - [ ] Hercules

### Test cases: 

- [ ] Engineering tests
  - [ ] Non-DA engineering test
  - [x] DA engineering test
    - [ ] Retro
    - [ ] Ensemble
    - [ ] Parallel
- [ ] RRFS fire weather
- [ ] RRFS_A:
- [ ] RRFS_B:
- [ ] RTMA:
- [ ] Others:

### CODE REVIEW

**Comment by BenjaminBlake-NOAA** [comment]
I just found references to the unneeded archive jobs that were also removed as part of PR #331 .  Before reviewing this PR let me also remove all archive variables.

**Comment by BenjaminBlake-NOAA** [comment]
Nevermind let's leave this PR as is.  I'll open another PR to remove references to the ARCHIVE and GRAPHICS jobs.  @MatthewPyle-NOAA  I know you prefer smaller PRs when possible  :)

**Comment by ShunLiu-NOAA** [comment]
Is there a way that we can keep the JEDIENVAR_IODA and IODA_PREPBUFR in the workflow since RRFSv2-JEDI will have to use IODA?

**Comment by BenjaminBlake-NOAA** [comment]
@ShunLiu-NOAA  I think we'll want to remove all aspects not needed for version 1 from the production/RRFS.v1 branch, but let's see what @MatthewPyle-NOAA thinks.  We could leave the JEDI/IODA material in the dev-sci branch.

**Comment by MatthewPyle-NOAA** [comment]
@ShunLiu-NOAA @BenjaminBlake-NOAA We won't clean the JEDI material out of the main dev-sci branch.  We're just cleaning up a version that will be what we hand off to NCO.

**Review by MatthewPyle-NOAA — APPROVED** [review]
Let the cleanup begin....

**Pull request merged**
