### PR TITLE
Move build-related scripts to sorc directory

### PR DESCRIPTION
**Pull request by chan-hoo**
## DESCRIPTION OF CHANGES: 

- Move the build-related scripts such as CMakeLists.txt, devbuild.sh, and Externals.cfg to the `sorc` directory.
- Rename `devbuild.sh` to `app_build.sh`.
- Update README and Read-the-Docs files.
- Build steps:
```
git clone -b feature/build https://github.com/chan-hoo/rrfs-workflow
cd rrfs-workflow/sorc
./manage_externals/checkout_externals
./app_build.sh -p=hera
```

## TESTS CONDUCTED: 

- On machines/platforms:

- [ ] WCOSS2
- [x] Hera
- [ ] Orion
- [ ] Jet

- Test cases: 

- [ ] Non-DA engineering test
- [ ] DA engineering test
- [ ] Other sample scripts:

## ISSUE: 

- Fixes the issue(s) mentioned in #45

### CODE REVIEW

**Review by BenjaminBlake-NOAA — APPROVED** [review]
@chan-hoo  The executables built successfully for me - thanks!  Approving now.  

One question I have is why was devbuild.sh renamed to app_build.sh?  Just curious.

**Comment by chan-hoo** [comment]
@BenjaminBlake-NOAA, `devbuild` means `build for development`. Initially, this script was used only by some developers (optionally) in the UFS SRW App. However, it is not optional any more (I think :) ). So, in my opinion, it's time to rename it. What do you think?

**Comment by hu5970** [comment]
> @BenjaminBlake-NOAA, `devbuild` means `build for development`. Initially, this script was used only by some developers (optionally) in the UFS SRW App. However, it is not optional any more (I think :) ). So, in my opinion, it's time to rename it. What do you think?

This rename sounds good to me. Thanks,

**Comment by BenjaminBlake-NOAA** [comment]
@chan-hoo @hu5970  I agree, thanks

**Review by hu5970 — APPROVED** [review]
I can successfully compile the code on WCOSS2.

**Review by MatthewPyle-NOAA — COMMENTED** [review]
One question is why the update_fork.pl was removed - was that intentional?

**Review by MatthewPyle-NOAA — APPROVED** [review]
Approving based on successful testing with the reorganized build script.

**Pull request merged**
