### PR TITLE
Update remaining post control files for latest UPP updates

### PR DESCRIPTION
**Pull request by BenjaminBlake-NOAA**
## DESCRIPTION OF CHANGES: 

- This PR updates the f01 post control xml file by adding in two hourly averaged smoke/dust fields (not relevant for f00) that were added with PR #366 .  In addition, the postxconfig text files for f00, f01, nosmokedust, nosmokedust_f00, and nosmokedust_f01 are updated/re-generated using the new rrfs_post_avblflds.xml and POST-XML-LIBRARY-NT.pl files.
## TESTS CONDUCTED: 

These changes were successfully tested with the RRFS fire weather nest which uses the "nosmokedust" versions of the postxconfig files.

### Machines/Platforms:

- WCOSS2
  - [x] Cactus/Dogwood
  - [ ] Acorn
- RDHPCS
  - [ ] Hera
  - [ ] Jet
  - [ ] Orion
  - [ ] Hercules

### Test cases: 

- [ ] Engineering tests
  - [ ] Non-DA engineering test
  - [ ] DA engineering test
    - [ ] Retro
    - [ ] Ensemble
    - [ ] Parallel
- [x] RRFS fire weather
- [ ] RRFS_A:
- [ ] RRFS_B:
- [ ] RTMA:
- [ ] Others:

### CODE REVIEW

**Comment by BenjaminBlake-NOAA** [comment]
@MatthewPyle-NOAA  Once I confirm your build fixes work in PR #369 I can run a quick test for this PR.  I'll convert it to a draft for now.

**Comment by MatthewPyle-NOAA** [comment]
@BenjaminBlake-NOAA Sounds good.

**Comment by hu5970** [comment]
@BenjaminBlake-NOAA @MatthewPyle-NOAA Current "fix/upp/postxconfig-NT-rrfs_f00.txt" and "fix/upp/postxconfig-NT-rrfs_f01.txt" do cause UPP crash. Please investigate. I am using fix/upp/postxconfig-NT-rrfs.txt for 00 and 01 h forecast for now.

Also, g2tmpl/1.12.0 is not lib in hpc-stack that RRFS is using. We need to add:

prepend_path("MODULEPATH"," /u/wen.meng/noscrub/ncep_post/g2tmpl/libs/modulefiles/compiler/intel/19.1.3.304")
load(pathJoin("g2tmpl", g2tmpl_ver))

Please check:
/lfs/h2/emc/lam/noscrub/emc.lam/rrfs/v0.9.3/rrfs-workflow/modulefiles/build_wcoss2_intel.lua
/lfs/h2/emc/lam/noscrub/emc.lam/rrfs/v0.9.3/rrfs-workflow/modulefiles/tasks/wcoss2/run_fcst.local.lua
/lfs/h2/emc/lam/noscrub/emc.lam/rrfs/v0.9.3/rrfs-workflow/modulefiles/tasks/wcoss2/save_restart.local.lua

for more changes needed to use g2tmpl/1.12.0 

Please commit those changes if  they are good.

Thanks,
Ming

**Comment by BenjaminBlake-NOAA** [comment]
@hu5970  Thanks for providing those additional changes.  I will test them on WCOSS2 and if they work I will add them to this PR.  I can confirm that using the previous version of UPP does work, so using the newer UPP version is the problem.

**Comment by MatthewPyle-NOAA** [comment]
@hu5970  g2tmpl/1.12.0 does exist on WCOSS2 - is the installed version not working to run things?  Or are you talking more about for non-WCOSS2 runs?

**Comment by MatthewPyle-NOAA** [comment]
@hu5970 It builds for me on WCOSS (just doublechecked), but I use --noifi --nogtg.  Maybe it is those components that create the problem with g2tmpl/1.12.0?

**Comment by BenjaminBlake-NOAA** [comment]
@MatthewPyle-NOAA @hu5970  I am still getting the same "list-directed I/O syntax" error in the UPP task when using the newest UPP from the RRFS release branch.  @EricJames-NOAA  have you seen this error with the latest version of UPP?

forrtl: severe (59): list-directed I/O syntax error, unit 22, file /lfs/h2/emc/stmp/Benjamin.Blake/rrfsfw/v0.9.1/2024051300/postprd/000/postxconfig-NT.txt

**Comment by hu5970** [comment]
> @hu5970 It builds for me on WCOSS (just doublechecked), but I use --noifi --nogtg. Maybe it is those components that create the problem with g2tmpl/1.12.0?

No problem. Please focus on solve NT problems. I will checkout the system and try it again after this PR. We can fix this if I still have problem.

**Comment by BenjaminBlake-NOAA** [comment]
@hu5970  @MatthewPyle-NOAA  I didn't realize POST-XML-LIBRARY-NT.pl was updated in the UPP repo, and I used an old version to generate the new postxconfig files.  Let me try re-creating them and see if that fixes things.

**Comment by EricJames-NOAA** [comment]
> @hu5970 @MatthewPyle-NOAA I didn't realize POST-XML-LIBRARY-NT.pl was updated in the UPP repo, and I used an old version to generate the new postxconfig files. Let me try re-creating them and see if that fixes things.

@BenjaminBlake-NOAA yes, POST-XML-LIBRARY-NT.pl was updated with one of my recent UPP PRs, which means the format of the postxconfig files has changed.  Let me know if you continue to have problems getting the latest UPP to run.

**Comment by BenjaminBlake-NOAA** [comment]
@EricJames-NOAA  Thanks for confirming!  Once I re-generate all the other postxconfig files with the update POST-XML-LIBRARY-NT.pl I think it should work and I will test it.

**Comment by BenjaminBlake-NOAA** [comment]
@MatthewPyle-NOAA Thanks, I think these changes are ready to be merged.  If/when the other product issues are resolved we may just have to update some of these files again.

**Review by MatthewPyle-NOAA — APPROVED** [review]
Getting this one merged...

**Pull request merged**
