### PR TITLE
Update module files to fix failure on Orion

### PR DESCRIPTION
**Pull request by chan-hoo**
## DESCRIPTION OF CHANGES: 

- Update module files to fix the failure on Orion
- Update path to fix files on Orion

## TESTS CONDUCTED: 

- On machines/platforms:

- [ ] WCOSS2
- [ ] Hera
- [x] Orion
- [ ] Jet

- Test cases: 

- [x] Non-DA engineering test
- [ ] DA engineering test
- [ ] Other sample scripts:

## ISSUE: 

- Fixes the issue(s) mentioned in #94

### CODE REVIEW

**Comment by chan-hoo** [comment]
The forecast task fails due to missing "globla_co2historicaldata_2024.txt" file in the designated directory. Once it is in, I'll test the task again.

**Comment by guoqing-noaa** [comment]
@chan-hoo Thanks for updating the rrfs-workflow for Orion. I made a minor change to prod-util similar to what was done on Hera/Jet and created a PR to your bugfix/orion branch. Hope that change can be included in this PR. Thanks!

**Comment by MatthewPyle-NOAA** [comment]
Want to wait on the CO2 files being updated so a complete engineering test can complete successfully.

**Comment by guoqing-noaa** [comment]
@MatthewPyle-NOAA co2 files have been copied to Orion and you may start the engineering tests. Thanks!

**Comment by chan-hoo** [comment]
@MatthewPyle-NOAA, with wtime_run_fcst=1:00:00, the eng test on Orion was completed successfully.

**Review by MatthewPyle-NOAA — APPROVED** [review]
Approving - thanks to everyone for getting Orion back as a viable platform to use.

**Pull request merged**
