### PR TITLE
1) Cycle smoke/dust at 06/18Z spinup cycle

### PR DESCRIPTION
**Pull request by hu5970**
1) Cycle smoke/dust at 06/18Z spinup cycle
     if 04/16Z smoke/dust cycle is skipped.
2) Bug fix boundary condition dependence (change or to and) 
3) Use rrfs_utl release branch.
4) Set UPP/prdgen for 15-min output.

Tested with RRFS_A v0.9.1 on Dogwood.

### CODE REVIEW

**Review by MatthewPyle-NOAA — COMMENTED** [review]
Looks okay to me at first glance, but will wait until tomorrow morning to approve/merge.

**Review by BenjaminBlake-NOAA — COMMENTED** [review]
@hu5970  Is the change in FV3LAM_wflow.xml needed?  The dependencies are already inside one `<and>` tag so I didn't think a second `<and>` tag would be needed.  Otherwise these changes look good to me, thanks

**Comment by hu5970** [comment]
> @hu5970 Is the change in FV3LAM_wflow.xml needed? The dependencies are already inside one `<and>` tag so I didn't think a second `<and>` tag would be needed. Otherwise these changes look good to me, thanks

Those <and> block is just for marking the whole boundary files as a group. We can remove it or keep it. It will not impact any thing.

**Review by BenjaminBlake-NOAA — APPROVED** [review]
@hu5970 Thanks, the changes look good to me.

**Review by MatthewPyle-NOAA — APPROVED** [review]
Will get this one merged...

**Pull request merged**
