### PR TITLE
Updating RRFS control files to be consistent with latest UPP.

### PR DESCRIPTION
**Pull request by EricJames-NOAA**
Update the UPP hash and UPP control files to the use the RRFSv1 release branch of UPP.

## DESCRIPTION OF CHANGES: 
Hash was updated to the latest develop (equivalent to release/rrfs_v1) and postxconfig files were updated.  

NOTE: Only the standard hourly and subh control files were updated...the other ones also need to be updated.

## TESTS CONDUCTED: 
Run in retrospective mode on Jet.

### Machines/Platforms:

- WCOSS2
  - [ ] Cactus/Dogwood
  - [ ] Acorn
- RDHPCS
  - [ ] Hera
  - [x] Jet
  - [ ] Orion
  - [ ] Hercules

### Test cases: 

- [ ] Engineering tests
  - [ ] Non-DA engineering test
  - [ ] DA engineering test
    - [ ] Retro
    - [ ] Ensemble
    - [ ] Parallel
- [ ] RRFS fire weather
- [x] RRFS_A:
- [ ] RRFS_B:
- [ ] RTMA:
- [ ] Others:

## ISSUE: 
None

### CODE REVIEW

**Comment by MatthewPyle-NOAA** [comment]
@EricJames-NOAA Seems like we can abandon PR #364 now since this PR goes to the UPP using g2tmpl 1.12.0, yes?

**Comment by EricJames-NOAA** [comment]
> @EricJames-NOAA Seems like we can abandon PR #364 now since this PR goes to the UPP using g2tmpl 1.12.0, yes?

@MatthewPyle-NOAA yes, I believe so!

**Review by MatthewPyle-NOAA — APPROVED** [review]
Looks good - approving

**Comment by BenjaminBlake-NOAA** [comment]
@MatthewPyle-NOAA  Would you like for me to update all the other post control xml and text files with these changes (f00, f01, nosmokedust)?  I can open a separate PR for that today.

**Pull request merged**
