### PR TITLE
Add FV3_HRRR_gf_nogwd CCPP suite to rrfs-workflow for fire weather grid

### PR DESCRIPTION
**Pull request by BenjaminBlake-NOAA**
## DESCRIPTION OF CHANGES: 

- In this PR, the FV3_HRRR_gf_nogwd CCPP physics suite is added to the workflow.  This CCPP physics suite is used with the RRFS fire weather grid.  Now that suite_FV3_HRRR_gf_nogwd.xml has been added to fv3atm via this PR (https://github.com/NOAA-EMC/fv3atm/pull/721), it can be removed from the parm directory of rrfs-workflow.  The build script also no longer needs the -rrfsfw option for copying the CCPP xml file from the parm directory.  Additional modifications are made to link_fix.sh, valid_param_vals.sh, and setup.sh.  The build and the make grid/orog/sfc_climo tasks were tested successfully on WCOSS2.

## TESTS CONDUCTED: 

- On machines/platforms:

- [x] WCOSS2
- [ ] Hera
- [ ] Orion
- [ ] Jet

- Test cases: 

- [ ] Non-DA engineering test
- [ ] DA engineering test
- [x] Other sample scripts: sample_configs/RRFSFW/config.sh_rrfsfw

## ISSUE: 

- Continues work on issue #15 

## CONTRIBUTORS (optional): 

@JiliDong-NOAA was able to add the FV3_HRRR_gf_nogwd CCPP physics suite to his PR to the fv3atm repository.

### CODE REVIEW

**Comment by chan-hoo** [comment]
@BenjaminBlake-NOAA, I got the following error in `make_ics`:
```
The variable "varmap_file" has not yet been specified for this physics
suite (CCPP_PHYS_SUITE):      
  CCPP_PHYS_SUITE = "FV3_HRRR_gf_nogwd"
```

**Comment by BenjaminBlake-NOAA** [comment]
@chan-hoo  I didn't think to test the make_ics job.  I see what needs to be fixed and I will push those changes to my PR soon.

**Comment by BenjaminBlake-NOAA** [comment]
@chan-hoo I made additional modifications to the make_orog, make_ics, make_lbcs, and run_fcst tasks in order to ensure that they work properly with the new CCPP physics suite.  Please rerun your test when you are able.  Thank you.  :)

**Comment by chan-hoo** [comment]
My test was complete successfully. Approving.

**Review by chan-hoo — APPROVED** [review]

**Review by MatthewPyle-NOAA — APPROVED** [review]

**Pull request merged**
