### PR TITLE
update model hash to fix nssl mp init issue and add MPI to compiling …

### PR DESCRIPTION
**Pull request by JiliDong-NOAA**
…option

## DESCRIPTION OF CHANGES: 

- This PR will fix the NSSL MP init issue described here:
https://github.com/ufs-community/ufs-weather-model/issues/2100

by updating model hash#. Furthermore, the fix will also need to have "-DMPI=ON" added in compiling options.
 
### Machines/Platforms:

- WCOSS2
  - [ ] Cactus/Dogwood
  - [ ] Acorn
- RDHPCS
  - [ ] Hera
  - [ ] Jet
  - [ ] Orion
  - [ ] Hercules

### Test cases: 

- [ ] Engineering tests
  - [ ] Non-DA engineering test
  - [ ] DA engineering test
    - [ ] Retro
    - [ ] Ensemble
    - [ ] Parallel
- [ ] RRFS fire weather
- [ ] RRFS_A:
- [ ] RRFS_B:
- [ ] RTMA:
- [ ] Others:

## ISSUE: 

- Fixes the issue(s) mentioned in #9999

### CODE REVIEW

**Comment by MatthewPyle-NOAA** [comment]
@JiliDong-NOAA Does adding this -DMPI=ON flag have any impact other than invoking the fix for NSSL MP runs?

**Comment by JiliDong-NOAA** [comment]
I don't think so. ufs-weather-model actually has "-DMPI=on" for regression tests. In ufs-weather-model/tests/compile.sh

`CMAKE_FLAGS+=" -DMPI=ON"`

**Comment by MatthewPyle-NOAA** [comment]
Thanks for confirming, @JiliDong-NOAA.  Figured that had to be the case

**Review by MatthewPyle-NOAA — APPROVED** [review]
Getting this one merged in....

**Pull request merged**
