### PR TITLE
cleanup to get ready for adding mpas+jedi components

### PR DESCRIPTION
**Pull request by guoqing-noaa**
The following files are kept:
```
doc/ (but updated)
ecf/
parm/wmo
versions/
```

The next PR will add back the following directories with corresponding files:
```
fix/
jobs/
modulefiles/
parm/config
scripts/
sorc/
ush/
util/
rocoto/
```

### CODE REVIEW

**Review by BenjaminBlake-NOAA — APPROVED** [review]

**Comment by BenjaminBlake-NOAA** [comment]
@guoqing-noaa The cleanup changes look good to me.  Thanks for your work on this.

**Review by MatthewPyle-NOAA — COMMENTED** [review]
Do we really want to delete almost everything?  I didn't expect this kind of PR, and feel like it doesn't match up with what was discussed in the meeting earlier this week.  Opinions @hu5970 @ShunLiu-NOAA ?

**Comment by ShunLiu-NOAA** [comment]
> Do we really want to delete almost everything? I didn't expect this kind of PR, and feel like it doesn't match up with what was discussed in the meeting earlier this week. Opinions @hu5970 @ShunLiu-NOAA ?

**Comment by ShunLiu-NOAA** [comment]
@MatthewPyle-NOAA as we discussed, I think we can keep some files in ./fix, and ./sorc, if we want to use the job name as the current rrfs, we can keep some EX scripts or JOB scripts. I guess it might be hard for building MPAS+JEDI using the existing scripts since both model and JEDI are new to rrfs. We can have a discussion on Monday. 
@guoqing-noaa Will deleting everything help you efficiently build up a new cycled DA system?

**Comment by guoqing-noaa** [comment]
@MatthewPyle-NOAA and @ShunLiu-NOAA Thanks for the review. I had thought we had agreed on a clean start as @hu5970 proposed in Monday's meeting.

@ShunLiu-NOAA Yes, it would be better to start from a clean point  (empty jobs/ scripts/, etc.)
We keep `ecf/  parm/wmo  versions/`.

**Comment by ShunLiu-NOAA** [comment]
@MatthewPyle-NOAA do you have any other concerns regarding @guoqing-noaa's changes? Do you think we need a tagup meeting to address this?

**Pull request merged**
