### PR TITLE
changed README and change CI to reflect new main branch

### PR DESCRIPTION
**Pull request by edwardhartnett**
## DESCRIPTION OF CHANGES: 
Updated README, also changing CI system, to handle new branch main.

## TESTS CONDUCTED: 
N/A

### Machines/Platforms:
N/A

### Test cases: 
N/A

## ISSUE: 
Part of #469

### CODE REVIEW

**Comment by edwardhartnett** [comment]
@MatthewPyle-NOAA after this is merged, go back to settings, and under branch protection you will be able to type in "docs" and "flake8" to make these required CI runs. That way, GitHub will enforce that these work.

**Review by BenjaminBlake-NOAA — DISMISSED** [review]

**Comment by MatthewPyle-NOAA** [comment]
@edwardhartnett I made a small addition to the README file - let me know if it is/isn't okay with you.

**Review by MatthewPyle-NOAA — APPROVED** [review]
Approving the first PR to "main"...

**Comment by MatthewPyle-NOAA** [comment]
> @MatthewPyle-NOAA after this is merged, go back to settings, and under branch protection you will be able to type in "docs" and "flake8" to make these required CI runs. That way, GitHub will enforce that these work.

@edwardhartnett Is this adding new branch protection rules?  Not intuitive to me where I need to add "docs" and "flake8"

**Pull request merged**
