### PR TITLE
Port rrfs-workflow to Hercules 

### PR DESCRIPTION
**Pull request by guoqing-noaa**
## DESCRIPTION OF CHANGES: 

- Port rrfs-workflow to Hercules 

## TESTS CONDUCTED: 

- On machines/platforms:

- [ ] WCOSS2
- [ ] Hera
- [x] Orion
- [x] Hercules
- [ ] Jet

- Test cases: 

- [x] Non-DA engineering test
- [ ] DA engineering test
- [x] Other sample scripts:
ush/sample_configs/others/config.sh.RRFS_CONUS_3km. Period: 1 February 2022.

## ISSUE: 

- Fixes the issue(s) mentioned in #171 

## CONTRIBUTORS (optional): 

@chan-hoo @ShawnMurdzek-NOAA @JacobCarley-NOAA

### CODE REVIEW

**Comment by chan-hoo** [comment]
@guoqing-noaa, thanks for this PR. I got the following error:
```
/usr/bin/env: ‘python’: No such file or directory
```
This is because `python` does not exist in `/usr/bin/env`. You can find a temporary solution for this here (aqm_dev):
https://github.com/ufs-community/ufs-srweather-app/commit/6884fb0f9c859b696392e3e75acc8d2ae20832c4#
I added a new file "checkout_externals_python3". If you have any better solution, you can do it :)
Hope someone opened a ticket for this to the hercules help desk.

**Comment by JacobCarley-NOAA** [comment]
I believe @JamesAbeles-NOAA is also working on a Hercules port. I am including him here for awareness.

**Comment by JacobCarley-NOAA** [comment]
One more thing, the GSI Utils folks are also working on porting to Hercules and [reported an MPI environment setting that is needed to be enabled to get things to run properly with netCDF4](https://github.com/NOAA-EMC/GSI-utils/pull/23#issuecomment-1864610112): `export I_MPI_EXTRA_FILESYSTEM=ON`. [This was also reported by the ufs-weather-model folks](https://github.com/ufs-community/ufs-weather-model/issues/2015#issuecomment-1864438186). I wanted to bring this up here in case anyone was not aware.

**Comment by guoqing-noaa** [comment]
@chan-hoo Right, this is because Hercules does not have a default Python env.  Users can `module load python` before checking out sorc and/or do app_build.sh.

One way to solve this is to describe this in README.md.
Another way is to add one line in app_build.sh before checkout_externals:
```
python --version
If [[ $? -ne 0 ]]; then
   module load python
fi
```
Let me know which method you guys prefer. Thanks!

**Comment by guoqing-noaa** [comment]
Another thing I'd like to mention is that I did not find the "yafyaml" library on Hercules. Currently, I commented it out in the Lua file. Do any scripts in rrfs-workflow use "yafyaml"?

**Comment by chan-hoo** [comment]
> @chan-hoo Right, this is because Hercules does not have a default Python env. Users can `module load python` before checking out sorc and/or do app_build.sh.
> 
> One way to solve this is to describe this in README.md. Another way is to add one line in app_build.sh before checkout_externals:
> 
> ```
> python --version
> if [[ $? -ne 0 ]]; then
>    module load python
> fi
> ```
> 
> The caveat of the second method is that it is only needed in Hercules.
> 
> Let me know which method you guys prefer. Thanks!

Vote for the second one (`app_build.sh`) :)

**Comment by guoqing-noaa** [comment]
> Vote for the second one (`app_build.sh`) :)
Good. I will make this change as voted, :)

**Comment by chan-hoo** [comment]
@guoqing-noaa, I got
```
 python: command not found
```

**Comment by guoqing-noaa** [comment]
> @guoqing-noaa, I got
> 
> ```
>  python: command not found
> ```
@chan-hoo This is expected on Hercules. Do you mean I need to suppress this error message? such as:
`python --version 1>/dev/null 2>/dev/null`

This error message will NOT stop the checkout process. However, Hercules has a performance issue today and now I cannot even do "ls". So it may look like "python not found" hangs the whole process just by reading the output message.

**Comment by chan-hoo** [comment]
Got it. I'll try it again tomorrow.

**Comment by guoqing-noaa** [comment]
@chan-hoo FYI, Hercules is back.

**Comment by chan-hoo** [comment]
@guoqing-noaa, I am testing it now. So far so good. I'll let you know once it is done.

**Comment by chan-hoo** [comment]
@guoqing-noaa, test was complete successfully. Approving. Happy Holidays! :)

**Review by chan-hoo — APPROVED** [review]

**Comment by MatthewPyle-NOAA** [comment]
Thanks for testing and approving, @chan-hoo

**Comment by guoqing-noaa** [comment]
Thanks, @chan-hoo @MatthewPyle-NOAA!  Happy holidays!

**Pull request merged**
