### PR TITLE
Updates UPP hash to get 15 minute product changes

### PR DESCRIPTION
**Pull request by MatthewPyle-NOAA**
## DESCRIPTION OF CHANGES: 

- Simple change to update the UPP hash

## TESTS CONDUCTED: 

- Confirmed that this update checked out the proper hash from UPP, and also confirmed (after updating the config files) that the time labeling problems and zero QPF in first hour or so seen previously is fixed with these changes.

### Machines/Platforms:

- WCOSS2
  - [x] Cactus/Dogwood
  - [ ] Acorn
- RDHPCS
  - [ ] Hera
  - [ ] Jet
  - [ ] Orion
  - [ ] Hercules

### Test cases: 

- [ ] Engineering tests
  - [x] Non-DA engineering test - but tweaked to generate 15 minute output and use the special RRFS control files
  - [ ] DA engineering test
    - [ ] Retro
    - [ ] Ensemble
    - [ ] Parallel
- [ ] RRFS fire weather
- [ ] RRFS_A:
- [ ] RRFS_B:
- [ ] RTMA:
- [ ] Others:

## ISSUE: 

- Hopefully fixes the issue(s) mentioned in #304

## CONTRIBUTORS (optional): 

Bringing in UPP changes courtesy of @EricJames-NOAA

### CODE REVIEW

**Review by BenjaminBlake-NOAA — DISMISSED** [review]

**Comment by EricJames-NOAA** [comment]
@MatthewPyle-NOAA we should probably update the postxconfig-NT-rrfs.txt and postxconfig-NT-rrfs_subh.txt files as well, to be consistent with this UPP.

**Comment by MatthewPyle-NOAA** [comment]
@EricJames-NOAA Let me know what needs to be changed - thanks!

**Comment by EricJames-NOAA** [comment]
@MatthewPyle-NOAA Looks like the postxconfig-NT-rrfs.txt is up to date.  Please update these three files from UPP:

https://github.com/NOAA-EMC/UPP/blob/develop/parm/postxconfig-NT-rrfs_subh.txt
https://github.com/NOAA-EMC/UPP/blob/develop/parm/post_avblflds.xml (named rrfs_post_avblflds.xml in rrfs-workflow)
https://github.com/NOAA-EMC/UPP/blob/develop/parm/rrfs_postcntrl_subh.xml

**Comment by MatthewPyle-NOAA** [comment]
@EricJames-NOAA Thanks for pointing the need to update the files.  Things look much better now.  To confirm, this "bucket1" functionality is creating 15 minute buckets within UPP for the subh times?  That was a pleasant surprise for me.

**Comment by MatthewPyle-NOAA** [comment]
@BenjaminBlake-NOAA Hold off on merging until we get more clarification from Eric James.

**Comment by EricJames-NOAA** [comment]
> @EricJames-NOAA Thanks for pointing the need to update the files. Things look much better now. To confirm, this "bucket1" functionality is creating 15 minute buckets within UPP for the subh times? That was a pleasant surprise for me.

This update is just for the labeling...I'm still just reading the run total accumulated QPF from the history file.  At some point we will presumably need to update UPP to read the new bucket fields from the history file, once those fields are available.  Is that right?

**Comment by EricJames-NOAA** [comment]
> > @EricJames-NOAA Thanks for pointing the need to update the files. Things look much better now. To confirm, this "bucket1" functionality is creating 15 minute buckets within UPP for the subh times? That was a pleasant surprise for me.
> 
> This update is just for the labeling...I'm still just reading the run total accumulated QPF from the history file. At some point we will presumably need to update UPP to read the new bucket fields from the history file, once those fields are available. Is that right?

These bucket1 fields were developed for HRRR...I thought it would be easier to just use them in RRFS too.

**Pull request closed without merging**
