### PR TITLE
Add f00 and f01 UPP text files to remove run total accumulation and hourly max/min fields

### PR DESCRIPTION
**Pull request by BenjaminBlake-NOAA**
## DESCRIPTION OF CHANGES: 

- In this PR, new postxconfig text files for f00 and f01 are added to the fix/upp directory.  At f00, we do not want to write out any hourly max/min fields or run total accumulation fields to UPP grib2 output.  At f01, we want the hourly max/min fields, but the run total accumulation fields are still not needed because they will be equivalent to the bucket (1-hour) accumulation fields.  The exrrfs_run_post.sh ex-script has been updated to use these special text files at f00 and f01.  Since USE_CUSTOM_POST_CONFIG_FILE is set to TRUE for the RRFS, the logic is added within that block of code.  I also set USE_CUSTOM_POST_CONFIG_FILE to TRUE for the RRFS fire weather nest since we will also want to use these UPP text files with it.
-  In addition, a few files in the fix/upp directory are renamed/modified to better adhere to the naming conventions used by current operational systems (e.g. HiResW, HRRR).  Those changes are:
- fv3lam_rrfs.xml -> rrfs_postcntrl.xml (postcntrl xml files are also added for f00 and f01).
- post_avblflds.xml -> rrfs_post_avblflds.xml (according to Matt we won't be pushing this file back to the UPP repository, so having it specific to the RRFS application should be fine)
- Delete fv3lam_post_avblflds.xml because it is no longer used
- postxconfig-NT-fv3lam_rrfs.txt -> postxconfig-NT-rrfs.txt
- There are some other files in the fix/upp directory which could also be renamed, such as fv3lam_rtma_NOAHLSM.xml, but I think that is outside the scope of this PR.
- I tested these changes with the non-DA engineering test.  I used the RRFS_CONUS_25km grid for my test but the changes would also work with the RRFS_NA_3km grid - that test would have been more expensive to run.

### Machines/Platforms:

- WCOSS2
  - [x] Cactus/Dogwood
  - [ ] Acorn
- RDHPCS
  - [ ] Hera
  - [ ] Jet
  - [ ] Orion
  - [ ] Hercules

### Test cases: 

- [ ] Engineering tests
  - [x] Non-DA engineering test
  - [ ] DA engineering test
    - [ ] Retro
    - [ ] Ensemble
    - [ ] Parallel
- [ ] RRFS fire weather
- [ ] RRFS_A:
- [ ] RRFS_B:
- [ ] RTMA:
- [ ] Others:

## ISSUE: 

- Fixes the issue(s) mentioned in #262 

## CONTRIBUTORS (optional): 

@AndrewBenjamin-NOAA

### CODE REVIEW

**Comment by BenjaminBlake-NOAA** [comment]
@MatthewPyle-NOAA  I would like @AndrewBenjamin-NOAA to have a chance to review this PR before we merge it.  Thanks!

**Comment by MatthewPyle-NOAA** [comment]
@BenjaminBlake-NOAA When you tested it, did you see that fields were not generated at f00 and f01?  In my test with the non-DA engineering test I see the 0-0 accum/max/min/avg type fields at f00, and also looks like the parm files come from sorc/UPP/parm/

```
cp /lfs/h2/emc/lam/noscrub/Matthew.Pyle/rrfs-workflow_postcntrl/sorc/UPP/parm/postxc
onfig-NT-fv3lam_rrfs.txt ./postxconfig-NT.txt
```

**Comment by BenjaminBlake-NOAA** [comment]
Thanks @MatthewPyle-NOAA , I forgot about the 1-h averaged fields which we obviously don't need at f00.  I made a mistake with leaving the hourly accumulation fields in for f00.  I removed the run total accumulation fields from f00 and f01, but the bucket (1-hour) accumulation fields should not be included at f00.  I'll remove those and run my own test, then commit changes to the f00 xml and text files.

**Comment by BenjaminBlake-NOAA** [comment]
I removed the following accumulation and 1-h average fields from f00 and completed a successful test on Cactus:
SNOWC, ASNOW (GSD_ACM_SNOD_ON_SURFACE), APCP, NCPCP, LSPA, FROZR, FRZR, TSNOWP, SNOM, SSRUN, BGRUN, LHTFL, SHTFL, GFLUX, SNOHF, EVP, PEVAP, WATR, TCDC, CDLYR, DSWRF, DLWRF, USWRF, ULWRF

25 records were removed from my f00 prslev file.  I left those FFG and ARI variables in the f00 postcntrl xml file, but if I need to remove them I can.  However I don't see them in the f00 output.

**Comment by MatthewPyle-NOAA** [comment]
I need to look into how the REFS processing code deals with ASNOW - I might need an f00 ASNOW field currently, but should be able to avoid it (I think).

**Comment by BenjaminBlake-NOAA** [comment]
Sounds good.  I can also re-add ASNOW at f00

**Comment by MatthewPyle-NOAA** [comment]
I'd say make it clean without f00 APCP/ASNOW type fields.  I'll need to make some script adjustments in the REFS.

**Comment by guoqing-noaa** [comment]
@BenjaminBlake-NOAA 
The change to "postxconfig-NT-rrfs.txt" will affect RTMA. Could you modify the following two files as well? Thanks!

`config.sh.RTMA_CONUS_3km`:CUSTOM_POST_CONFIG_FP="$(cd "$( dirname "${BASH_SOURCE[0]}" )/.." &>/dev/null&&pwd)/fix/upp/postxconfig-NT-fv3lam_rrfs.txt"

`config.sh.RTMA_NA_3km`:CUSTOM_POST_CONFIG_FP="$(cd "$( dirname "${BASH_SOURCE[0]}" )/.." &>/dev/null&&pwd)/fix/upp/postxconfig-NT-fv3lam_rrfs.txt"

**Comment by BenjaminBlake-NOAA** [comment]
@guoqing-noaa  Sure!  I just updated the config files.

**Review by MatthewPyle-NOAA — APPROVED** [review]
My test forcing the use of the new f00 and f01 files looked good to me.  Thanks for the product cleanup.

**Comment by AndrewBenjamin-NOAA** [comment]
Thanks for including me in the review @BenjaminBlake-NOAA . The changes look good, I just had a few questions:

1. Did you rename the xml and txt files from what they are in UPP so that the f00 and f01 files would be consistent?
2. When there are changes in UPP, will you need to rename those files every time?

**Comment by BenjaminBlake-NOAA** [comment]
@AndrewBenjamin-NOAA  Thanks for taking a look!
1. I renamed the xml and txt files to get rid of "fv3lam" and to more closely match the naming conventions used by the operational HiResW and HRRR.  For example, the HRRR uses hrrr_postcntrl.xml and hrrr_postcntrl_anl.xml for f00.
2. That is a good question and ultimately I think we should update the names in the UPP repo to match the new names here.

**Pull request merged**
