### PR TITLE
update the hash of the rrfs_bridgeloan repo

### PR DESCRIPTION
**Pull request by guoqing-noaa**
## DESCRIPTION OF CHANGES: 

update the hash of the rrfs_bridgeloan repo

## TESTS CONDUCTED: 

- On machines/platforms:

- [ ] WCOSS2
- [ ] Hera
- [x] Orion
- [x] Jet

- Test cases: 

- [x] Non-DA engineering test
- [ ] DA engineering test
- [ ] Other sample scripts:

## ISSUE: 

- Fixes the issue(s) mentioned in #76

### CODE REVIEW

**Comment by chan-hoo** [comment]
@guoqing-noaa, the change in this pr has been already include in the rrfs-workflow (but not in the same way). The copy commands to replace several source codes in the weather model with a fixed version can be found in 'sorc/app_build.sh' (https://github.com/NOAA-EMC/rrfs-workflow/blob/b325b2668c543a6272582c5b22f44f13f7d21a95/sorc/app_build.sh#L469). The reason why we put them in app_build.sh rather than `checkout_external` itself is that this is a temporary fix and this change would not be valid for other hashes. You can check the following PR for the details (https://github.com/NOAA-EMC/rrfs-workflow/pull/54/files). @hu5970 also agreed with this approach. Please let us know what you think about this.

**Comment by chan-hoo** [comment]
@guoqing-noaa, regarding the `Init.sh`, there is an if-statement for this in `ush/generate_FV3LAM_wflow.sh` (https://github.com/NOAA-EMC/rrfs-workflow/blob/b325b2668c543a6272582c5b22f44f13f7d21a95/ush/generate_FV3LAM_wflow.sh#L118). So, I think we don't have to run it in the build script `app_build.sh`. Please let us know what you think about this.

**Comment by MatthewPyle-NOAA** [comment]
@guoqing-noaa I don't believe the CODEOWNERS file has the control for this repository.  But I did add you to the "RRFS-devs" team on the NOAA-EMC github (Ming Hu already is there) that we do use to control access.

**Comment by guoqing-noaa** [comment]
> @guoqing-noaa, the change in this pr has been already included in the rrfs-workflow (but not in the same way). The copy commands to replace several source codes in the weather model with a fixed version can be found in `sorc/app_build.sh` (
> 
> https://github.com/NOAA-EMC/rrfs-workflow/blob/b325b2668c543a6272582c5b22f44f13f7d21a95/sorc/app_build.sh#L469
> 
> ). The reason why we put them in app_build.sh rather than `manage_externals/checkout_external` itself is that this is a temporary fix and this change would not be valid for other hashes. You can check the following PR for the details (https://github.com/NOAA-EMC/rrfs-workflow/pull/54/files). @hu5970 also agreed with this approach. Please let us know what you think about this.

Hi @chan-hoo Thanks!
I did not notice that the copy is now done in app_build.sh. I would think it is fine to do copying anywhere.

The only thing is that as you mentioned, this is a temporary fix and this fix may change (slowly) with time. In our previous opinion, it may be better to handle it separately in the bridge_loan.sh without the need to update the app_build.sh. However, updating app_build.sh is not a big deal now. Also, running "bridge_loan.sh" may give users explicit information what files are changed in a temporary fix.  
There are just some miniature considerations, and I don't think we need to make any changes now.

**Comment by guoqing-noaa** [comment]
> @guoqing-noaa, regarding the `Init.sh`, there is an if-statement for this in `ush/generate_FV3LAM_wflow.sh` (
> 
> https://github.com/NOAA-EMC/rrfs-workflow/blob/b325b2668c543a6272582c5b22f44f13f7d21a95/ush/generate_FV3LAM_wflow.sh#L118
> 
> ). So, I think we don't have to run it in the build script `app_build.sh`. Please let us know what you think about this.

Hi @chan-hoo Yes, if "Init.sh" does not run at the checkout_externals time, it will be done at workflow generation time. This is a backup plan at the ufs-srweather-app era. Also at that time, someone may checkout regional_workflow alone and this acts as a safeguard measure to make sure fix files are linked correctly.
It is still better to run "init.sh" right after checkout_externals as one may work on changing fix files directly without a need to generate a workflow.

**Comment by guoqing-noaa** [comment]
> @guoqing-noaa I don't believe the CODEOWNERS file has the control for this repository. But I did add you to the "RRFS-devs" team on the NOAA-EMC github (Ming Hu already is there) that we do use to control access.

Good to know. Thanks, @MatthewPyle-NOAA !

**Comment by chan-hoo** [comment]
@guoqing-noaa, it makes sense to me in case that `regional_workflow` is one of the external components. However, in rrfs-workflow, we don't have to check out the workflow separately as one component (with a hash) any more. I am doubting that it is still a valid approach. I understand there is a case that someone may need to run the `Init.sh` file without generating a workflow. However, even in this case, they don't have to run `manage_externals/checkout_externals` either. Did I miss something?

**Comment by guoqing-noaa** [comment]
> @guoqing-noaa, it makes sense to me in case that `regional_workflow` is one of the external components. However, in rrfs-workflow, we don't have to check out the workflow separately as one component (with a hash) any more. I am doubting that it is still a valid approach. I understand there is a case that someone may need to run the `Init.sh` file without generating a workflow. However, even in this case, they don't have to run `manage_externals/checkout_externals` either. Did I miss something?

@chan-hoo Right, I am still implicitly in the thought of regional_workflow as a separate repo. One can just run Init.sh directly instead of  `manage_externals/checkout_externals`  in the situation I mentioned. Thanks!

**Comment by guoqing-noaa** [comment]
> @MatthewPyle-NOAA, since @guoqing-noaa agreed, we can close this PR without merging.

@chan-hoo I would want to update the hash for the rrfs_bridgeloan repo. rrfs-workflow uses `ufs-weather-model` instead of `ufs_weather_model`.

**Comment by chan-hoo** [comment]
@guoqing-noaa, oops! I am sorry. I didn't catch it. Approving now.

**Review by chan-hoo — APPROVED** [review]

**Review by MatthewPyle-NOAA — APPROVED** [review]
Thanks to @chan-hoo and @guoqing-noaa for sorting it all out.  Definitely good with a simple hash update!

**Comment by guoqing-noaa** [comment]
@chan-hoo @MatthewPyle-NOAA Thank you very much for the discussions and quick actions!

**Pull request merged**
