### PR TITLE
Add WMO header process

### PR DESCRIPTION
**Pull request by hsinmulin-NOAA**
## DESCRIPTION OF CHANGES: 

-
1. Build WMO headers from the templates and locate them in the /fix/prdgen/ (wmo-header-awips, wmo-header-warp, wmo-header-ifi)
2. add "rrfs.prslev-rrfs3km.params" in /fix/pedgen for na3km (3km rotate lat-lon) subtracting process per needs
3. Refine "rrfs_prdgen_faa_subpiece.sh" for sub-hourly capacity and WMO header process
4.  New "rrfs.wmo-header.sh" for the process of adding WHO header to specific files.
5. Refine "rrfs_subset_ifi_304m.sh" to be able to add WMO header 
6.  Update ""rrfs_prdgen_faa_subpiece.sh" to include CONUS 3km Lambert Conformal IFI & GTG 

## TESTS CONDUCTED: 

All the code change has been merged to the updated RRFS workflow and process in WCOSS2 foe sensitivity test.  The results are expected and successfully compared to the default.

### Machines/Platforms:

- WCOSS2
  - [x] Cactus/Dogwood
  - [ ] Acorn
- RDHPCS
  - [ ] Hera
  - [ ] Jet
  - [ ] Orion
  - [ ] Hercules

### Test cases: 

- [ ] Engineering tests
  - [x] Non-DA engineering test
  - [ ] DA engineering test
    - [ ] Retro
    - [ ] Ensemble
    - [ ] Parallel
- [ ] RRFS fire weather
- [ ] RRFS_A:
- [ ] RRFS_B:
- [ ] RTMA:
- [ ] Others:

## ISSUE: 

- Fixes the issue(s) mentioned in #9999

### CODE REVIEW

**Review by MatthewPyle-NOAA — COMMENTED** [review]
Could all of these new wmo header files be moved to parm/wmo/ ?  A lot of wmo headers were added there previously, and that is where they need to be for operations.

**Comment by hsinmulin-NOAA** [comment]
Yes, it can.
I will move them there and modify the related script

Thanks

Lin

**Comment by BenjaminBlake-NOAA** [comment]
@hsinmulin-NOAA I think the files currently in parm/wmo can be removed and replaced with yours.  They were added with PR #283 but are not actually being used by RRFS right now.  @MatthewPyle-NOAA is that correct?

**Comment by MatthewPyle-NOAA** [comment]
@BenjaminBlake-NOAA @hsinmulin-NOAA Correct, they haven't been used.  I just added what Andrew Benjamin had created into the workflow for future use.

**Comment by hsinmulin-NOAA** [comment]
Awesome, thanks!

**Comment by hsinmulin-NOAA** [comment]
@Matthew Pyle - NOAA Federal ***@***.***>
The reason to put those files in /fix/prodgen/wmo-header-* are
1. They are not directly used by the RRFS or UPP, instead of by the prdgen
process
2. The current way is more organized for various needs and easy to control,
instead of putting all the files (more than hundred and potentially more)
in one place.
3. The current parm/wmo is not used anywhere in the workflow, just created
for potential use.
4. There will be some scripts need to be changed
If another product in the current production is set in this way
(parm/wmo), we better follow it, otherwise, it is beneficial to be at
current setup.

**Comment by MatthewPyle-NOAA** [comment]
@hsinmulin-NOAA Having them in parm/wmo is an operational requirement, so it needs to be done even if you don't like it done that way.  Sorry we don't have more flexibility here.

**Comment by hsinmulin-NOAA** [comment]
No problem, I understand.  I will modify that.

**Comment by hsinmulin-NOAA** [comment]
WMO header file has been moved to /parm/wmo.
The related scripts are also updated to reflect the change.  The new
workflow generates identical results as the previous setup.

**Review by MatthewPyle-NOAA — APPROVED** [review]
Thanks for putting things under parm/wmo, @hsinmulin-NOAA - approving.

**Pull request merged**
