### PR TITLE
Initial merge of feature/RRFS_dev1 branches of App and workflow with their commit histories

### PR DESCRIPTION
**Pull request by chan-hoo**
- Initial merge of two `feature/RRFS_dev1` branches of NOAA-GSL UFS SRW App and regional workflow repositories.
- This is just to check that the two repositories are combined with their commit histories.
- This PR does not work as it is.
- This PR resolves the issue #2

### CODE REVIEW

**Comment by chan-hoo** [comment]
@MatthewPyle-NOAA, this is for the initial merge test. I just combine two repositories of app and workflow to check their commit histories.

**Comment by MatthewPyle-NOAA** [comment]
@chan-hoo Should we push this to develop, or isolate it somewhere more temporary?

**Comment by chan-hoo** [comment]
@MatthewPyle-NOAA, in my opinion, we can merge this to develop and use it as a starting point because nobody uses this repo officially yet.

**Comment by MatthewPyle-NOAA** [comment]
Just want to make others are on board with this - was your understanding that GSL would want to bring in their RRFS_dev1 branch as an RRFS_dev1 branch under this repository?

**Comment by chan-hoo** [comment]
What I understood in the meeting was 1) they want to have the commit history, and 2) they want to add many GSL colleagues to the codeowner list. The list can be updated later.

**Comment by chan-hoo** [comment]
The UFS SRW app has many other branches for sub-projects while this repository is only for RRFS. Therefore, the 'develop' branch makes sense to me.

**Comment by chan-hoo** [comment]
@MatthewPyle-NOAA, can you merge this PR to check that the commit history is preserved. If not, you should merge them directly (not through a PR) or please give me the write permission for this repository.

**Review by MatthewPyle-NOAA — APPROVED** [review]
Approving as it is just a test to see if the history is preserved with Chan-Hoo's approach

**Comment by chan-hoo** [comment]
Yes. please do not squash it.

**Comment by chan-hoo** [comment]
@MatthewPyle-NOAA, thanks! It looks worked correctly as we expected.

**Pull request merged**
