### PR TITLE
[production/RRFS.v1] Utilize compath.py in setting COM directory paths

### PR DESCRIPTION
**Pull request by BenjaminBlake-NOAA**
## DESCRIPTION OF CHANGES: 

- In this PR, all definitions of COM directories in the J-jobs now utilize the compath.py function.  The COMROOT variable needs to be defined in order for compath.py to work properly, so COMROOT is set to ${PTMP}/com by default.  You can see the new example directory structure from my DA engineering test on Dogwood: /lfs/h2/emc/ptmp/Benjamin.Blake/test_da/com
- Also included here are some of the changes from PR #392 , specifically the changes to remove g2tmpl from modulefiles where it is not needed.  I felt that the date updates to config files from this PR were not necessary to add.

## TESTS CONDUCTED: 

These changes were tested with a spinup cycle of the DA engineering test.  All the jobs that were tested were able to utilize compath.py properly.

### Machines/Platforms:

- WCOSS2
  - [x] Cactus/Dogwood
  - [ ] Acorn
- RDHPCS
  - [ ] Hera
  - [ ] Jet
  - [ ] Orion
  - [ ] Hercules

### Test cases: 

- [ ] Engineering tests
  - [ ] Non-DA engineering test
  - [x] DA engineering test
    - [ ] Retro
    - [ ] Ensemble
    - [x] Parallel
- [ ] RRFS fire weather
- [ ] RRFS_A:
- [ ] RRFS_B:
- [ ] RTMA:
- [ ] Others:

## ISSUE: 

- Fixes issue #400

### CODE REVIEW

**Review by MatthewPyle-NOAA — COMMENTED** [review]
Looks good to me, but do have a few questions:  

Does ENSCTRL_COMOUT need to be treated differently from the "regular" COMOUT?  Could it also be defined with a compath.py kind of line?  I realize it currently isn't handled within the J-jobs, but should it be?  These are mostly rhetorical questions since I don't know the details on how it is used.

**Comment by MatthewPyle-NOAA** [comment]
@BenjaminBlake-NOAA that sounds good to me.  I can go ahead and approve/merge this one if that is okay with you.

**Comment by BenjaminBlake-NOAA** [comment]
@MatthewPyle-NOAA Yes that sounds good to me if the rest of the changes look good to you, thanks.

**Review by MatthewPyle-NOAA — APPROVED** [review]
Will approve this one, with expectation of a follow on PR to clean up some small details (task complete text files).

**Pull request merged**
