### PR TITLE
change task names (cycinit --> prep_ic, cycbdys --> prep_lbc)

### PR DESCRIPTION
**Pull request by hu5970**
1) Change cycinit and cycbdys to prep_ic and prep_lbc.
2) Use group task to run lbc even with 1 group.
3) Check the forecast log err file to decide the status of the forecast.

Tested with real-time CONUS 3km MPAS runs on JET.

### CODE REVIEW

**Comment by guoqing-noaa** [comment]
The changes look good to me.   

A minor comment: Suggest changing the title to something like `rename tasks cycinit and cycbdys to prep_ic and prep_lbc`

**Review by guoqing-noaa — APPROVED** [review]

**Comment by hu5970** [comment]
Do not know how to rename this PR.

**Review by MatthewPyle-NOAA — APPROVED** [review]
Looks good to me - thanks for the exrrfs_fcst.sh script change, also.

**Comment by hu5970** [comment]
@guoqing-noaa @MatthewPyle-NOAA Thanks for quick reviewing and merging. Ming

**Comment by MatthewPyle-NOAA** [comment]
No problem, @hu5970.  Good to get a quick victory every once in a while.

**Pull request merged**
