### PR TITLE
Fix failure with FV3GFS_FILE_FMT_ICS/LBCS=netcdf

### PR DESCRIPTION
**Pull request by chan-hoo**
## DESCRIPTION OF CHANGES: 

- Fix failure when the format of the FV3GFS input file is netcdf.
- Add non-DA sample scripts for netcdf.
- Change `maxtries_run_post` to 2.

## TESTS CONDUCTED: 

- On machines/platforms:

- [x] WCOSS2
- [x] Hera
- [x] Orion
- [ ] Jet

- Test cases: 

- [x] Non-DA engineering test
- [x] DA engineering test (on Hera)
- [ ] Other sample scripts:

## ISSUE: 

- Fixes the issue(s) mentioned in #61

### CODE REVIEW

**Comment by MatthewPyle-NOAA** [comment]
Changes seemed okay to me based on looking at differences, and in the process of running a test on WCOSS2 (to refamiliarize myself with running the workflow as much as anything).

**Review by MatthewPyle-NOAA — APPROVED** [review]
Looks good from my perspective.  @chan-hoo is your preference to get this bugfix merged ahead of your err_exit PR?

**Review by BenjaminBlake-NOAA — APPROVED** [review]
The changes look good to me.

For operations, will we support both grib2 and netcdf for the GFS IC/LBC files?

**Comment by MatthewPyle-NOAA** [comment]
@BenjaminBlake-NOAA I'd say having support for both netcdf and GRIB2 files to initialize is a good thing.

**Comment by BenjaminBlake-NOAA** [comment]
@MatthewPyle-NOAA  Agreed!

**Pull request merged**
