### PR TITLE
Updates the rrfs .xml and .txt file used by RRFS_A, and corrects a post issue for 15 minute output

### PR DESCRIPTION
**Pull request by MatthewPyle-NOAA**
## DESCRIPTION OF CHANGES: 

- Folds in the product changes made in recent UPP PRs (I was mistakenly thinking we pulled those directly into the system).  This removes things like VVEL, and goes away from certain local definitions of fields.

- While looking at v0.9.1 products earlier, noticed that the special "f00" and "f01" product list files weren't being used.  Changed the script logic to key on the new post_fhr variable that is designed to work properly with 15 minute products

## TESTS CONDUCTED: 

- Not tested yet, but plan to test as a local change within v0.9.1.  Won't merge until it is validated in this way.

### Machines/Platforms:

- WCOSS2
  - [x] Cactus/Dogwood
  - [ ] Acorn
- RDHPCS
  - [ ] Hera
  - [ ] Jet
  - [ ] Orion
  - [ ] Hercules

### Test cases: 

- [ ] Engineering tests
  - [ ] Non-DA engineering test
  - [ ] DA engineering test
    - [ ] Retro
    - [ ] Ensemble
    - [ ] Parallel
- [ ] RRFS fire weather
- [x] RRFS_A: in dev v0.9.1 system
- [ ] RRFS_B:
- [ ] RTMA:
- [ ] Others:

## ISSUE: 

- Fixes the issue(s) mentioned in #313

### CODE REVIEW

**Review by BenjaminBlake-NOAA — COMMENTED** [review]
@MatthewPyle-NOAA  The changes look good to me.  I can approve once a test completes successfully.  

One question I have is regarding the removal of VVEL.  Is VVEL being removed from all output at all levels?  I'm not as familiar with all the recent UPP changes so I apologize if I missed a discussion somewhere.  One of the RRFS plots I generate is 700-mb omega + RH, so if we remove VVEL then I won't be able to include vertical motion on those plots anymore.

**Comment by MatthewPyle-NOAA** [comment]
Thanks @BenjaminBlake-NOAA We're really trying to push people to use the more appropriate DZDT form of vertical motion (a w field with units of m/s)    I think we've scrubbed all isobaric VVEL records now - might still be a random VVEL on the lowest model level, or something similar.

**Comment by BenjaminBlake-NOAA** [comment]
@MatthewPyle-NOAA Thanks, I forgot about DZDT.  I can use that one for the vertical motion in my 700 mb plots instead of VVEL.

**Comment by MatthewPyle-NOAA** [comment]
@BenjaminBlake-NOAA I slipped in the three modified files as local changes in the v0.9.1 late yesterday, and do see the intended product changes, and also see that it is using the special f00 and f01 files when needed.

**Review by BenjaminBlake-NOAA — APPROVED** [review]
Thanks @MatthewPyle-NOAA , I also checked one of the v0.9.1 grib2 files and noticed all the VVEL fields were removed (except for VVEL at hybrid level 1).

**Pull request merged**
