### PR TITLE
update three SD fix files provided by Johana

### PR DESCRIPTION
**Pull request by guoqing-noaa**

### CODE REVIEW

**Comment by guoqing-noaa** [comment]
@JohanaRomeroAlvarez I've copied your new files to $FIX_RRFS on Jet/Hera/Orion/Hercules. This PR will enable the workflow to use the new SD fix files.

@ShunLiu-NOAA @hu5970  Could you sync the following three new files to WCOSS2? Thanks!
```
/scratch2/BMC/rtrr/FIX_RRFS/smoke_dust/RRFS_NA_3km/veg_map.nc.20240715
/scratch2/BMC/rtrr/FIX_RRFS/smoke_dust/RRFS_CONUS_3km/veg_map.nc.20240715
/scratch2/BMC/rtrr/FIX_RRFS/smoke_dust/RRFS_CONUS_3km/weight_file.nc.20240715
```

**Comment by ShunLiu-NOAA** [comment]
@guoqing-noaa is there any impact on the forecast with this update?

**Comment by guoqing-noaa** [comment]
> @guoqing-noaa is there any impact on the forecast with this update?

My impression is it will not. @JohanaRomeroAlvarez  Could you help answer this question from your experiments? Thanks!

**Comment by JohanaRomeroAlvarez** [comment]
> > @guoqing-noaa is there any impact on the forecast with this update?
> 
> My impression is it will not. @JohanaRomeroAlvarez Could you help answer this question from your experiments? Thanks!

@ShunLiu-NOAA 
We have updated the emissions factors map to distinguish between grassland and cropland fires. This map is used to estimate the magnitudes of smoke emissions. The update specifically impacts the categorization of these two types of fires, particularly in the eastern regions of the US, and will help us better manage prescribed fires. While the changes are targeted and should not be dramatic, there may be some minor impacts on the forecast for these specific fire types.

**Comment by ShunLiu-NOAA** [comment]
@JohanaRomeroAlvarez Thank you for your reply.
@guoqing-noaa The files are copied to WCOSS2. But it looks like the different method are used to handle smoke-dust fix files on WCOSS2. We will start the test of these fix files on Cactus first.

**Comment by ShunLiu-NOAA** [comment]
is the absence of "weight_file.nc" for RRFS_NA_3km intended?

**Comment by JohanaRomeroAlvarez** [comment]
> is the absence of "weight_file.nc" for RRFS_NA_3km intended?
Updating the weight_file.nc for RRFS_NA_3km is not required. We have revised the weight_file.nc for RRFS_CONUS_3km to ensure consistency with the RRFS_NA_3km file. Both files preserve the original values from RAVE without applying any averaging or weighting

**Review by MatthewPyle-NOAA — APPROVED** [review]
Confirmed that these are being used successfully in the real-time RRFS_A system.

**Pull request merged**
