### PR TITLE
Bugfix ensinit blending

### PR DESCRIPTION
**Pull request by delippi**
## DESCRIPTION OF CHANGES: 

- Changes to enable ensinit (1tstep ensemble initialization) and blending. Let the workflow decide which to use.
  - This fixes the issue of initializing the RRFS EnKF. In order to perform blending we need to have the 1h RRFS EnKF restarts. If the EnKF crashes or there is a production switch we will initialize the EnKF ensemble using the previous method which was to run the ensinit (1tstep) method using cold starts from the 6h GDAS. If all runs well, the blending will run and continuously cycling the RRFS EnKF and blending large scale perturbations from 6h GDAS for select variables. 
- An optimization change was also made for blending.

## TESTS CONDUCTED: 

- On machines/platforms:

- [x] WCOSS2
- [ ] Hera
- [ ] Orion
- [ ] Jet

- Test cases: 

- [ ] Non-DA engineering test
- [x] DA engineering test
- [ ] Other sample scripts:

## ISSUE: 

-

### CODE REVIEW

**Comment by MatthewPyle-NOAA** [comment]
@delippi Is this PR still a draft, or should it be made ready for review?  Sounds like getting this blending into the RT RRFS_A could happen in coming weeks, so would be good to get the workflow ready for it.

**Comment by delippi** [comment]
Hi @MatthewPyle-NOAA, I think these changes might be ready for review since I was able to test them myself in a short retro.

**Comment by delippi** [comment]
@MatthewPyle-NOAA, could we add @hu5970 to the review since he was working with me on some of this?

**Comment by MatthewPyle-NOAA** [comment]
@delippi - sure, made a review request from him.

**Comment by MatthewPyle-NOAA** [comment]
@delippi With these updates based on Ming's testing, is it ready to go?

**Review by hu5970 — APPROVED** [review]

**Comment by delippi** [comment]
@MatthewPyle-NOAA Yes, it is ready to go. Ming has already approved. There seems to be no issue with blending, but we had a model crash on the NA domain in the real-time so we have more testing/investigation to do. Ming wanted to have these changes merged and have blending turned off for now to do some other testing in the mean time.

**Review by MatthewPyle-NOAA — APPROVED** [review]
One question for the long term is the need for a special "BLENDINGPYTHON" version of python.  Does it include functionality not in the regular 3.8.6 install on WCOSS?  Will the regular install eventually have everything that is needed?  Just looking ahead to an eventual implementation.

**Comment by ShunLiu-NOAA** [comment]
@MatthewPyle-NOAA It is a good question. As we discussed previously, blending method call a fortran lib in python, I am not sure if it is the best way for implementation.

**Pull request merged**
