### PR TITLE
Establishes lossy compression for RRFS_A configuration

### PR DESCRIPTION
**Pull request by MatthewPyle-NOAA**
## DESCRIPTION OF CHANGES: 

- Modifies some variables for the model_configure file to allow for invoking lossy compression with the latest UFS code.   Namely adds `quantize_mode` and `quantize_nsd`.  Default option is for compression to be off.  RRFS_A sample configs that previously wrote netcdf_parallel output now are  using lossy compression with quantize_nsd=18.  

## TESTS CONDUCTED: 

- Settings were tested in off-line tests of the model.
-  
### Machines/Platforms:

- WCOSS2
  - [x] Cactus/Dogwood
  - [ ] Acorn
- RDHPCS
  - [x] Hera
  - [ ] Jet
  - [ ] Orion
  - [ ] Hercules

### Test cases: 

- [ ] Engineering tests
  - [x] Non-DA engineering test - ran with and without adding the two new variable definitions into the var_defns.sh file.
  - [ ] DA engineering test
    - [ ] Retro
    - [ ] Ensemble
    - [ ] Parallel
- [ ] RRFS fire weather
- [x] RRFS_A:  Generated RRFS_A workflow to see that the needed compression variables made it into the var_defns.sh files.
- [ ] RRFS_B:
- [ ] RTMA:
- [ ] Others:  

## ISSUE: 

- Fixes the issue(s) mentioned in #190

### CODE REVIEW

**Comment by MatthewPyle-NOAA** [comment]
Won't shift it back to a draft PR, but have one more small change to make to it.

**Comment by BenjaminBlake-NOAA** [comment]
@MatthewPyle-NOAA  I'd like to run a non-DA engineering test with these changes before approving.  I should be able to get to it on Monday.  Thanks

**Comment by MatthewPyle-NOAA** [comment]
@BenjaminBlake-NOAA sounds good.  These changes shouldn't impact that test - by default they really just impact RRFS_A.

**Review by BenjaminBlake-NOAA — COMMENTED** [review]
@MatthewPyle-NOAA  Ahh ok, then perhaps I don't need to run any additional tests since you already completed successful offline tests.

One quick question before I approve, related to removing lines 78-81 from create_model_configure_file.py: Does that mean WRTCMP_ideflate is now always 0 by default, unless one of the RRFS configurations is used, in which case it will always be 1?

**Comment by MatthewPyle-NOAA** [comment]
We could modify that, but I didn't like the forced connection between netcdf_parallel and ideflate.  I wanted to make things more flexible.   But we certainly could add compression to more if not all of the sample_configs options if we want.

**Comment by BenjaminBlake-NOAA** [comment]
I also do not like the forced connection between netcdf_parallel and ideflate, and I think your approach is better.  Thanks!

**Comment by MatthewPyle-NOAA** [comment]
@BenjaminBlake-NOAA Actually I'll go ahead and add compression to the other sample_config files that are using netcdf_parallel.  I probably was overly focused on RRFS_A.

**Review by BenjaminBlake-NOAA — APPROVED** [review]

**Comment by BenjaminBlake-NOAA** [comment]
Sure that makes sense, I just approved the PR but I agree about adding compression to the other config files.

**Comment by BenjaminBlake-NOAA** [comment]
@MatthewPyle-NOAA  Sounds good, and sure I can re-approve if/when your Hera tests are successful.

**Comment by MatthewPyle-NOAA** [comment]
@BenjaminBlake-NOAA  Despite some Hera issues (https://github.com/NOAA-EMC/rrfs-workflow/issues/226), the model ran okay with and without compression there.  I feel good about it being approved.

**Review by BenjaminBlake-NOAA — APPROVED** [review]
Thanks for opening an issue about the unrelated error on Hera.  Approving now!

**Pull request merged**
