### PR TITLE
Make DA tasks work on Hera and WCOSS2

### PR DESCRIPTION
**Pull request by chan-hoo**
## DESCRIPTION OF CHANGES: 

- Update the hashes of the external components.
- Update j-job and ex- scripts to make the DA part work on Hera and WCOSS2.
- Update the rocoto XML file for DA.
- Add the sample scripts for the DA engineering test.
- Move the sample scripts into the `ush/sample_configs` directory
- Add the flag `DO_NON_DA_RUN` for the non-DA test runs.
- Update the template and README file.

## TESTS CONDUCTED: 

- On machines/platforms:

- [x] WCOSS2
- [x] Hera
- [ ] Orion
- [ ] Jet

- Test cases: 

- [x] Non-DA engineering test
- [x] DA engineering test
- [ ] Other sample scripts:

## ISSUE: 

- Fixes the issue(s) mentioned in #7

### CODE REVIEW

**Comment by BenjaminBlake-NOAA** [comment]
@chan-hoo Thanks for putting this together, I should be able to run a test before I go on leave Thursday/Friday.  Would it be more helpful if I ran the test on a different platform other than Hera like WCOSS2 or Jet?

**Comment by chan-hoo** [comment]
@ShunLiu-NOAA, can you test this PR on wcoss2 with your parallel run script?

**Comment by chan-hoo** [comment]
@MatthewPyle-NOAA, I think it would be better to test this PR on Hera first as the tile describes. I am testing this PR on wcoss2. We can open a new PR later if it is necessary for wcoss2. If there is no need to update for wcoss2 before this PR is merged, I'll change the title and description and let you know.

**Review by MatthewPyle-NOAA — COMMENTED** [review]
I wasn't sure if I understood the meaning of this flag: DO_NONDA

Is it meaning that it is a run made without any DA?  If so, I'm wondering if something like DO_NON-DA-RUN would make things clearer (at least to someone like me).

**Comment by ShunLiu-NOAA** [comment]
> @BenjaminBlake-NOAA, Ming suggested me to use a different sample script for each machine. I just tested it on Hera (it is still running now though). I am trying to run a real-time case on WCOSS2 now but I have some issues. At this moment, this PR works only on Hera.

**Comment by chan-hoo** [comment]
@MatthewPyle-NOAA, changed to 'DO_NON_DA_RUN'.

**Comment by chan-hoo** [comment]
@MatthewPyle-NOAA @ShunLiu-NOAA, can you re-open this PR?

**Comment by ShunLiu-NOAA** [comment]
> @ShunLiu-NOAA, can you test this PR on wcoss2 with your parallel run script?

@chan-hoo For the test on WCOSS2, should I use sample_configs/config.RRFS_CONUS_3km.sh to generate "conus" workflow?

**Comment by chan-hoo** [comment]
@ShunLiu-NOAA, you've closed this PR (by mistake ??). Please re-open this first. Please hold the test for a while. I'll have to update the 'run' module list for run_fcst on wcoss2.

**Comment by ShunLiu-NOAA** [comment]
got it.

**Comment by chan-hoo** [comment]
@ShunLiu-NOAA @MatthewPyle-NOAA, please test this PR on wcoss2 as well.

**Comment by chan-hoo** [comment]
@ShunLiu-NOAA, you can use `ush/sample_configs/DA_eng/config.DA.para.wcoss2.sh`. You can try other sample scripts in `sample_configs` but I didn't test them.

**Comment by MatthewPyle-NOAA** [comment]
@chan-hoo Today is my only day working this week, so not sure if I can test it on WCOSS2 soon.  Sorry I haven't been much help at getting this PR through the process.

**Comment by BenjaminBlake-NOAA** [comment]
@chan-hoo @MatthewPyle-NOAA  I am back from leave and will be able to test this PR on WCOSS2.  Hoping to get to it later today

**Review by BenjaminBlake-NOAA — COMMENTED** [review]
@chan-hoo  I am testing this PR on WCOSS2 today.  The 12Z make_lbcs tasks ran successfully, and I believe the whole system should cold start with the 15Z cycle and the make_ics task.

After reviewing the changes, I have one question.  Why was dt_atmos changed from 36 to 40 in set_predef_grid_params.sh for the RRFS_CONUS_3km grid?  I thought the real-time parallel was using dt_atmos = 36.

Otherwise the changes look good to me unless I run into any issues during testing.  Thanks!

**Comment by chan-hoo** [comment]
@BenjaminBlake-NOAA, I set it to be the same as that in the original workflow. If it is 36 in the real-time parallel, I'll change the default value to 36.

**Comment by BenjaminBlake-NOAA** [comment]
@chan-hoo Sounds good, yes I recommend using dt_atmos = 36.  Thanks!

**Comment by chan-hoo** [comment]
Changed.

**Comment by BenjaminBlake-NOAA** [comment]
@chan-hoo  My jobs seemed to be working fine, but now everything on Dogwood is running super slowly and jobs are hanging.  The ./launch_FV3LAM_wflow.sh command takes several minutes to complete when it should take about 5 seconds, and the prep_cyc_spinup task which completed in ~6 minutes for a previous cycle just timed out at 20 minutes.  I may have to revisit my testing tomorrow.  

I did encounter the issue with the cldanl_nonvar task where I had to use rocotocomplete to mark the task as completed,  So before this PR gets merged we will need to come up with a solution.

**Comment by chan-hoo** [comment]
@BenjaminBlake-NOAA, the original workflow has the same issue on the cldanl_nonvar task on wcoss2 too. I think it would be better for Ming or Shun to open a PR to fix this issue.

**Comment by BenjaminBlake-NOAA** [comment]
@chan-hoo  That sounds like a good plan!  I found one more small issue that shouldn't take long to fix.

For the prep_cyc_spinup task at 04Z and 16Z, the FVCOM processing needs the C3359_fvcom_mask.nc file in the fix_lam directory in order to run (C3463_fvcom_mask.nc for the 3-km NA grid).  So when the workflow gets generated we need to add that file to the fix_lam directory.  @ShunLiu-NOAA how was this issue fixed in the real-time parallel?

**Comment by chan-hoo** [comment]
Got it. I'll add it to the script.

**Comment by ShunLiu-NOAA** [comment]
@BenjaminBlake-NOAA and @chan-hoo 
realtime parallel is using
/lfs/h2/emc/lam/noscrub/emc.lam/FIX_RRFS/lam/RRFS_NA_3km_C3463_Lake_fracSV.
@hu5970 could you let Ben and Chan-hoo know how to configure this directory?

**Comment by chan-hoo** [comment]
@BenjaminBlake-NOAA, I've added the soft-link to the fvcom_mask.nc to "fix/lam/RRFS_NA_3km/". Can you test it?

**Comment by BenjaminBlake-NOAA** [comment]
@chan-hoo  The links work for me for the RRFS_CONUS_3km and RRFS_NA_3km grids.  Thanks!

**Review by BenjaminBlake-NOAA — APPROVED** [review]
My tests on WCOSS2 were successful, approving this PR.  Thanks @chan-hoo for all your work on this

**Review by MatthewPyle-NOAA — APPROVED** [review]
With Ben's successful test, will go ahead and approve and merge.

**Pull request merged**
