### PR TITLE
Update nems.configure and model_configure templates

### PR DESCRIPTION
**Pull request by chan-hoo**
## DESCRIPTION OF CHANGES: 

- Add `PRINT_ESMF` to the `nems.configure` template.
- Add some missing parameters for output which exist in the original workflow to the `model_configure` template.
- Add  `USE_CRON_TO_RELAUNCH` to the non-DA sample scripts.
- Replace the bash scripts to create `diag_table` and `model_configure` with the python scripts.

## TESTS CONDUCTED: 

- On machines/platforms:

- [x] WCOSS2
- [x] Hera
- [ ] Orion
- [ ] Jet

- Test cases: 

- [x] Non-DA engineering test
- [x] DA engineering test
- [ ] Sample script:

## ISSUE: 

- Fixes the issue(s) mentioned in #16.

### CODE REVIEW

**Comment by BenjaminBlake-NOAA** [comment]
@chan-hoo  What tests would you like me to run for this PR?  I should have time tomorrow to work on it

**Comment by chan-hoo** [comment]
@BenjaminBlake-NOAA, I've merged the latest PR and I am running the non-DA test on Hera. I'll let you know which one you can do.

**Comment by chan-hoo** [comment]
@MatthewPyle-NOAA, There are a couple of reasons that this PR is useful for rrfs-workflow. 1) To turn off "PRINT_ESMF" (prevent from print out ESMF log files), the `nems.confure` should be updated. 2) some print-out parameters were missing in my previous PR. These are necessary for some sample scripts that I didn't test. 3) In my opinion, python script is more useful (powerful) for this kind of work (filling out a template with parameter values). This change also makes rrfs-workflow closer to the ufs-srw-app, and it will be easy to bring any changes necessary for rrfs-workflow from the ufs-srw-app in the future.

**Comment by MatthewPyle-NOAA** [comment]
@chan-hoo Thanks for the explanation and background on the reason for this PR.

**Comment by chan-hoo** [comment]
@BenjaminBlake-NOAA, you can test this PR with either the non-DA or DA sample script.

**Comment by BenjaminBlake-NOAA** [comment]
@chan-hoo  Sounds good.  I'll test it on Jet with the non-DA sample script since WCOSS2 is down today, and you already tested that one on Hera.

**Review by BenjaminBlake-NOAA — COMMENTED** [review]
@chan-hoo  My test completed successfully on Hera.  I didn't realize Jet was going down for maintenance today and it kicked me off while I was setting things up.

One quick question before I submit my approval - what was the reasoning behind the change from single quotes to double quotes throughout fill_jinja_template.py?

**Comment by chan-hoo** [comment]
@BenjaminBlake-NOAA, both single and double quotes should work, but double quotes can contain single quotes as part of the string (theoretically). I didn't make this change for the script. I copied the recent version of `fill_jinaj_template.py` from the UFS SRW App. Someone made this change there.

**Review by BenjaminBlake-NOAA — APPROVED** [review]

**Review by MatthewPyle-NOAA — APPROVED** [review]
No show stoppers looking through the changes, and with successful tests already completed will go ahead and merge.

**Pull request merged**
